_wandb:
    value:
        cli_version: 0.19.0
        m: []
        python_version: 3.11.10
        t:
            "1":
                - 1
                - 41
                - 55
            "2":
                - 1
                - 41
                - 55
            "3":
                - 16
                - 23
                - 55
            "4": 3.11.10
            "5": 0.19.0
            "8":
                - 5
            "12": 0.19.0
            "13": linux-x86_64
checkpoint:
    value: /scratch/alpine/zhli3162/.cache/sam/sam_vit_h_4b8939.pth
dataset:
    value: PACO
model:
    value: Molmo+SAM
molmo_model:
    value: Molmo-7B-D-0924
